export const strings = {
  title: "Student Payment Tracker",
  subtitle: "Balances by fee for the current academic year and term.",
  fee: {
    label: "Fee",
    tabs: {
      all: "All fees",
      tuition: "Tuition",
      bus: "Bus",
      registration: "Registration",
      clubs: "Clubs",
    },
  },
  summary: {
    totalDue: "Outstanding balance",
    totalCollected: "Total collected",
    students: (n: number) => (n === 1 ? "1 student" : `${n} students`),
    collectionRate: (pct: string) => `${pct}% collection rate`,
  },
  recordCount: (n: number) => (n === 1 ? "1 record" : `${n} records`),
  search: {
    placeholder: "Search by name, ID, or contact…",
    clear: "Clear search",
  },
  filters: {
    label: "Filters:",
    gradeLevelLabel: "Grade level",
    gradeLabel: "Class",
    statusLabel: "Status",
    allGradeLevels: "All grade levels",
    allGrades: "All classes",
    allStatuses: "All statuses",
    clearAll: "Clear filters",
    activeCount: (n: number) => (n === 1 ? "1 filter active" : `${n} filters active`),
  },
  columns: {
    id: "ID",
    student: "Student",
    class: "Class",
    due: "Due",
    paid: "Paid",
    // The all-fees rollup adds year-scoped tuition/registration to the current
    // term's bus/club charges. Different scopes, so the header names them
    // rather than implying one amount owed right now.
    totalDue: "Total due (year + current term)",
    totalPaid: "Total paid",
    status: "Status",
    lastPayment: "Last payment",
  },
  status: {
    paid: "Paid",
    partial: "Partial",
    unpaid: "Unpaid",
    none: "—",
  },
  // Progress of paid against due, for screen readers.
  paidProgress: (paid: string, due: string) => `${paid} paid of ${due}`,
  noPayment: "—",
  empty: "No students.",
  emptyFiltered: "No students match the current filters.",
  emptyFee: "No students hold a charge for this fee.",
  loading: "Loading…",
  error: "Failed to load students.",
  pagination: {
    prev: "Previous",
    next: "Next",
    pageIndicator: (page: number, totalPages: number) =>
      `Page ${page} of ${totalPages}`,
    rowCount: (shown: number, total: number) =>
      `Showing ${shown} of ${total}`,
  },
  toasts: {
    profileSaved: "Student details saved.",
    tuitionSaved: "Tuition updated.",
    feeAdded: "Fee added.",
    feeUpdated: "Fee updated.",
    feeDeleted: "Fee deleted.",
  },
  detail: {
    back: "Back to students",
    studentId: (code: string) => `Student ID: ${code}`,
    categoryNew: "New student",
    categoryReturning: "Returning student",
    tabs: {
      fees: "Fees overview",
      history: "Payment history",
    },
    personal: {
      title: "Personal information",
      class: "Class",
      teacher: "Teacher",
      firstName: "First name",
      lastName: "Last name",
      parentEmail: "Parent email",
      parentPhone: "Parent phone",
      contract: "Tuition contract",
      empty: "—",
      edit: "Edit",
      save: "Save changes",
      saving: "Saving…",
      cancel: "Cancel",
      saveError: "Could not save changes. Please try again.",
      readonlyHint: "Class, teacher, and contract are managed elsewhere.",
    },
    tuition: {
      title: "Tuition breakdown",
      base: "Base tuition",
      net: "Net tuition",
      noCharge: "No tuition charge for this year.",
      edit: "Edit",
      save: "Save changes",
      saving: "Saving…",
      cancel: "Cancel",
      saveError: "Could not save changes. Please try again.",
      discountName: "Discount name",
      discountNamePlaceholder: "e.g. Sibling discount",
      addDiscount: "Add discount",
      removeDiscount: "Remove discount",
      paidHint: (paid: string) => `${paid} already paid — net can't go below this.`,
      chooseDiscount: "Choose a discount",
      customValueMnt: "Amount (₮)",
      customValuePercent: "Percent (%)",
      moveUp: "Move up",
      moveDown: "Move down",
      legacyTag: "legacy",
      orderHint: "Discounts apply top to bottom, each onto the running total.",
      noCatalog: "No discounts in the catalog yet.",
      // How a discount reads: "10%" or "300,000₮".
      expressed: (unit: "mnt" | "percent", value: number): string =>
        unit === "percent"
          ? `${value}%`
          : `${value.toLocaleString("en-US")}₮`,
      sibling: "Sibling",
      siblingSelect: "Link the sibling student",
      siblingSearch: "Search by name or ID…",
      siblingNoMatch: "No students match.",
      siblingClear: "No sibling linked",
      siblingEnrolled: "Enrolled this year",
      siblingNotEnrolled: "Not enrolled this year",
      siblingLabel: (name: string) => `Sibling: ${name}`,
    },
    annual: {
      title: "One-time & annual fees",
      empty: "No annual charges for this year.",
    },
    charge: {
      addFee: "Add fee",
      addTitle: "Add fee",
      editTitle: "Edit fee",
      feeName: "Fee name",
      feeNamePlaceholder: "e.g. Bus, Uniform, Tennis",
      scope: "Applies to",
      scopeAnnual: "Whole year",
      scopeTerm: "A term",
      term: "Term",
      amount: "Amount (₮)",
      notes: "Notes",
      notesPlaceholder: "Optional note",
      save: "Save",
      saving: "Saving…",
      cancel: "Cancel",
      remove: "Delete fee",
      removing: "Deleting…",
      removeConfirm: "Delete this fee? This can't be undone.",
      removeBlocked: "This fee has payments, so it can't be deleted.",
      editAria: (fee: string) => `Edit ${fee}`,
      error: "Could not save. Please try again.",
      paidFloor: (paid: string) => `${paid} already paid — amount can't go below this.`,
    },
    term: {
      title: "Term-based fees",
      feeType: "Fee",
      current: "Current",
      total: "Total",
      empty: "No term-based charges for this year.",
      notEnrolled: "—",
    },
    columns: {
      fee: "Fee",
      category: "Category",
      amount: "Amount",
      status: "Status",
      paid: "Paid",
      balance: "Balance",
      date: "Date",
      reference: "Reference",
      sender: "Sender",
      memo: "Memo",
    },
    totals: {
      label: "Total",
      charged: "Charged",
      paid: "Paid",
      balance: "Balance",
    },
    history: {
      empty: "No payments recorded yet.",
      subtitle: (name: string) => `Recorded payments for ${name}.`,
    },
    // Human labels for the raw fee_name values. Falls back to a prettified
    // version of the stored name (club fees carry their own display names).
    feeLabel: (feeName: string): string => {
      const known: Record<string, string> = {
        tuition: "Tuition",
        registration: "Registration",
        bus_fee: "Bus fee",
        bus: "Bus fee",
      };
      return (
        known[feeName] ??
        feeName.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
      );
    },
  },
};
